# Generated by Django 6.0.5 on 2026-05-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_benefit_job_company_job_companylocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefit',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='gallery',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='required',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.JSONField(),
        ),
    ]
