# Generated by Django 6.0.5 on 2026-05-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_employer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='gallery',
        ),
    ]
